name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.36.64.18 << 'EOF'
            if [ ! -d "~/ticketing_project" ]; then
               git clone https://github.com/datbg152/ticket-booking-system.git ~/ticketing_project
            fi
            cd ~/ticketing_project
            git pull origin main
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod 600 .env  # Secure the .env file
            
            docker-compose down
            docker-compose up -d --build
          EOF